const hskData = [
  {hz: "你好", py: "nǐ hǎo", vi: "Xin chào", exHz: "你好向，很高兴认识你。", exPy: "Nǐ hǎo, hěn gāoxìng rènshi nǐ.", exVi: "Xin chào, rất vui được gặp bạn."},
  {hz: "谢谢", py: "xièxie", vi: "Cảm ơn", exHz: "谢谢你的帮助。", exPy: "Xièxie nǐ de bāngzhù.", exVi: "Cảm ơn sự giúp đỡ của bạn."},
  {hz: "再见", py: "zàijiàn", vi: "Tạm biệt", exHz: "明天见，再见！", exPy: "Míngtiān jiàn, zàijiàn!", exVi: "Hẹn gặp lại ngày mai!"},
  {hz: "我", py: "wǒ", vi: "Tôi", exHz: "我是中国人。", exPy: "Wǒ shì Zhōngguó rén.", exVi: "Tôi là người Trung Quốc."},
  {hz: "你", py: "nǐ", vi: "Bạn", exHz: "你叫什么名字？", exPy: "Nǐ jiào shénme míngzi?", exVi: "Bạn tên là gì?"},
  {hz: "他", py: "tā", vi: "Anh ấy", exHz: "他是我的朋友。", exPy: "Tā shì wǒ de péngyou.", exVi: "Anh ấy là bạn tôi."},
  {hz: "她", py: "tā", vi: "Cô ấy", exHz: "她很漂亮。", exPy: "Tā hěn piàoliang.", exVi: "Cô ấy rất xinh đẹp."},
  {hz: "是", py: "shì", vi: "Là", exHz: "这是我的书。", exPy: "Zhè shì wǒ de shū.", exVi: "Đây là sách của tôi."},
  {hz: "不", py: "bù", vi: "Không", exHz: "我不是学生。", exPy: "Wǒ bú shì xuésheng.", exVi: "Tôi không phải học sinh."},
  {hz: "的", py: "de", vi: "Của", exHz: "这是我的书。", exPy: "Zhè shì wǒ de shū.", exVi: "Đây là sách của tôi."},
  {hz: "吗", py: "ma", vi: "Không? (nghi vấn)", exHz: "你好吗？", exPy: "Nǐ hǎo ma?", exVi: "Bạn khỏe không?"},
  {hz: "呢", py: "ne", vi: "Còn... thì sao?", exHz: "你呢？", exPy: "Nǐ ne?", exVi: "Còn bạn thì sao?"},
  {hz: "喜欢", py: "xǐhuan", vi: "Thích", exHz: "我喜欢吃中国菜。", exPy: "Wǒ xǐhuan chī Zhōngguó cài.", exVi: "Tôi thích ăn món Trung Quốc."},
  {hz: "爱", py: "ài", vi: "Yêu", exHz: "我爱你。", exPy: "Wǒ ài nǐ.", exVi: "Tôi yêu bạn."},
  {hz: "有", py: "yǒu", vi: "Có", exHz: "我有一个妹妹。", exPy: "Wǒ yǒu yí ge mèimei.", exVi: "Tôi có một em gái."},
  {hz: "在", py: "zài", vi: "Ở", exHz: "他在家。", exPy: "Tā zài jiā.", exVi: "Anh ấy ở nhà."},
  {hz: "什么", py: "shénme", vi: "Cái gì", exHz: "这是什么？", exPy: "Zhè shì shénme?", exVi: "Đây là cái gì?"},
  {hz: "谁", py: "shéi", vi: "Ai", exHz: "他是谁？", exPy: "Tā shì shéi?", exVi: "Anh ấy là ai?"},
  {hz: "哪", py: "nǎ", vi: "Nào", exHz: "你去哪儿？", exPy: "Nǐ qù nǎr?", exVi: "Bạn đi đâu?"},
  {hz: "几", py: "jǐ", vi: "Mấy", exHz: "现在几点？", exPy: "Xiànzài jǐ diǎn?", exVi: "Bây giờ mấy giờ?"},
  {hz: "多少", py: "duōshao", vi: "Bao nhiêu", exHz: "多少钱？", exPy: "Duōshao qián?", exVi: "Bao nhiêu tiền?"},
  {hz: "怎么", py: "zěnme", vi: "Làm sao", exHz: "怎么去？", exPy: "Zěnme qù?", exVi: "Đi như thế nào?"},
  {hz: "一", py: "yī", vi: "Một", exHz: "一个人。", exPy: "Yí ge rén.", exVi: "Một người."},
  {hz: "二", py: "èr", vi: "Hai", exHz: "二月。", exPy: "Èr yuè.", exVi: "Tháng hai."},
  {hz: "三", py: "sān", vi: "Ba", exHz: "三天。", exPy: "Sān tiān.", exVi: "Ba ngày."},
  {hz: "四", py: "sì", vi: "Bốn", exHz: "四个苹果。", exPy: "Sì ge píngguǒ.", exVi: "Bốn quả táo."},
  {hz: "五", py: "wǔ", vi: "Năm", exHz: "五月。", exPy: "Wǔ yuè.", exVi: "Tháng năm."},
  {hz: "六", py: "liù", vi: "Sáu", exHz: "六点。", exPy: "Liù diǎn.", exVi: "Sáu giờ."},
  {hz: "七", py: "qī", vi: "Bảy", exHz: "七天。", exPy: "Qī tiān.", exVi: "Bảy ngày."},
  {hz: "八", py: "bā", vi: "Tám", exHz: "八月。", exPy: "Bā yuè.", exVi: "Tháng tám."},
  {hz: "九", py: "jiǔ", vi: "Chín", exHz: "九个人。", exPy: "Jiǔ ge rén.", exVi: "Chín người."},
  {hz: "十", py: "shí", vi: "Mười", exHz: "十块钱。", exPy: "Shí kuài qián.", exVi: "Mười khối tiền."},
  {hz: "百", py: "bǎi", vi: "Trăm", exHz: "一百。", exPy: "Yì bǎi.", exVi: "Một trăm."},
  {hz: "千", py: "qiān", vi: "Nghìn", exHz: "一千。", exPy: "Yì qiān.", exVi: "Một nghìn."},
  {hz: "人", py: "rén", vi: "Người", exHz: "中国人。", exPy: "Zhōngguó rén.", exVi: "Người Trung Quốc."},
  {hz: "朋友", py: "péngyou", vi: "Bạn bè", exHz: "我的朋友。", exPy: "Wǒ de péngyou.", exVi: "Bạn tôi."},
  {hz: "老师", py: "lǎoshī", vi: "Giáo viên", exHz: "他是老师。", exPy: "Tā shì lǎoshī.", exVi: "Anh ấy là giáo viên."},
  {hz: "学生", py: "xuésheng", vi: "Học sinh", exHz: "我是学生。", exPy: "Wǒ shì xuésheng.", exVi: "Tôi là học sinh."},
  {hz: "医生", py: "yīshēng", vi: "Bác sĩ", exHz: "她是医生。", exPy: "Tā shì yīshēng.", exVi: "Cô ấy là bác sĩ."},
  {hz: "妈妈", py: "māma", vi: "Mẹ", exHz: "我妈妈很好。", exPy: "Wǒ māma hěn hǎo.", exVi: "Mẹ tôi rất tốt."},
  {hz: "爸爸", py: "bàba", vi: "Bố", exHz: "我爸爸是老师。", exPy: "Wǒ bàba shì lǎoshī.", exVi: "Bố tôi là giáo viên."},
  {hz: "儿子", py: "érzi", vi: "Con trai", exHz: "我的儿子。", exPy: "Wǒ de érzi.", exVi: "Con trai tôi."},
  {hz: "女儿", py: "nǚ'ér", vi: "Con gái", exHz: "我的女儿。", exPy: "Wǒ de nǚ'ér.", exVi: "Con gái tôi."},
  {hz: "哥哥", py: "gēge", vi: "Anh trai", exHz: "我哥哥很高。", exPy: "Wǒ gēge hěn gāo.", exVi: "Anh trai tôi rất cao."},
  {hz: "弟弟", py: "dìdi", vi: "Em trai", exHz: "我弟弟是学生。", exPy: "Wǒ dìdi shì xuésheng.", exVi: "Em trai tôi là học sinh."},
  {hz: "姐姐", py: "jiějie", vi: "Chị gái", exHz: "我姐姐是医生。", exPy: "Wǒ jiějie shì yīshēng.", exVi: "Chị gái tôi là bác sĩ."},
  {hz: "妹妹", py: "mèimei", vi: "Em gái", exHz: "我妹妹很漂亮。", exPy: "Wǒ mèimei hěn piàoliang.", exVi: "Em gái tôi rất xinh."},
  {hz: "先生", py: "xiānsheng", vi: "Ông/Ngài", exHz: "王先生你好。", exPy: "Wáng xiānsheng nǐ hǎo.", exVi: "Chào ông Vương."},
  {hz: "小姐", py: "xiǎojiě", vi: "Cô", exHz: "李小姐很漂亮。", exPy: "Lǐ xiǎojiě hěn piàoliang.", exVi: "Cô Lý rất xinh."},
  {hz: "家", py: "jiā", vi: "Nhà", exHz: "我在家。", exPy: "Wǒ zài jiā.", exVi: "Tôi ở nhà."},
  {hz: "学校", py: "xuéxiào", vi: "Trường học", exHz: "我去学校。", exPy: "Wǒ qù xuéxiào.", exVi: "Tôi đi học."}
];