const hskData = [
    { hz: "爱", py: "ài", vi: "yêu", exHz: "我爱你。", exPy: "Wǒ ài nǐ.", exVi: "Tôi yêu bạn." },
    { hz: "八", py: "bā", vi: "tám", exHz: "他有八个苹果。", exPy: "Tā yǒu bā ge píngguǒ.", exVi: "Anh ấy có tám quả táo." },
    { hz: "爸爸", py: "bàba", vi: "bố", exHz: "我的爸爸很高。", exPy: "Wǒ de bàba hěn gāo.", exVi: "Bố của tôi rất cao." },
    { hz: "杯子", py: "bēizi", vi: "cốc", exHz: "这是我的杯子。", exPy: "Zhè shì wǒ de bēizi.", exVi: "Đây là cốc của tôi." },
    { hz: "北京", py: "Běijīng", vi: "Bắc Kinh", exHz: "北京很大。", exPy: "Běijīng hěn dà.", exVi: "Bắc Kinh thì lớn." },
    { hz: "本", py: "běn", vi: "cuốn (dùng cho sách)", exHz: "这本书很有趣。", exPy: "Zhè běn shū hěn yǒuqù.", exVi: "Quyển sách này rất thú vị." },
    { hz: "不客气", py: "bú kèqì", vi: "không có gì (đáp lại lời cảm ơn)", exHz: "不客气。", exPy: "bú kèqì.", exVi: "Không có gì." },
    { hz: "不", py: "bù", vi: "không", exHz: "他不喜欢吃鱼。", exPy: "Tā bù xǐhuān chī yú.", exVi: "Anh ấy không thích ăn cá." },
    { hz: "菜", py: "cài", vi: "món ăn, rau củ", exHz: "我喜欢吃菜。", exPy: "Wǒ xǐhuān chī cài.", exVi: "Tôi thích ăn rau." },
    { hz: "茶", py: "chá", vi: "trà", exHz: "我喝茶。", exPy: "Wǒ hē chá.", exVi: "Tôi uống trà." },
    { hz: "吃", py: "chī", vi: "ăn", exHz: "我吃苹果。", exPy: "Wǒ chī píngguǒ.", exVi: "Tôi ăn táo." },
    { hz: "出租车", py: "chūzūchē", vi: "taxi", exHz: "我坐出租车。", exPy: "Wǒ zuò chūzūchē.", exVi: "Tôi đi taxi." },
    { hz: "打电话", py: "dǎ diànhuà", vi: "gọi điện thoại", exHz: "她给我打电话。", exPy: "Tā gěi wǒ dǎ diànhuà.", exVi: "Cô ấy gọi điện cho tôi." },
    { hz: "大", py: "dà", vi: "lớn, to", exHz: "这件衣服很大。", exPy: "Zhè jiàn yīfú hěn dà.", exVi: "Cái áo này rất to." },
    { hz: "的", py: "de", vi: "của (thuộc tính)", exHz: "这是我的书。", exPy: "Zhè shì wǒ de shū.", exVi: "Đây là sách của tôi." },
    { hz: "点", py: "diǎn", vi: "giờ (trong thời gian)", exHz: "现在是三点。", exPy: "Xiànzài shì sān diǎn?", exVi: "Bây giờ là mấy giờ?" },
    { hz: "电脑", py: "diànnǎo", vi: "máy tính", exHz: "我用电脑。", exPy: "Wǒ yòng diànnǎo.", exVi: "Tôi dùng máy tính." },
    { hz: "电视", py: "diànshì", vi: "ti vi", exHz: "电视很大。", exPy: "Diànshì hěn dà.", exVi: "Tivi thì lớn." },
    { hz: "电影", py: "diànyǐng", vi: "phim", exHz: "我喜欢看电影。", exPy: "Wǒ xǐhuān kàn diànyǐng.", exVi: "Tôi thích xem phim." },
    { hz: "东西", py: "dōngxī", vi: "đồ vật, thứ", exHz: "这是什么东西？", exPy: "Zhè shì shénme dōngxī?", exVi: "Đây là cái gì?" },
    { hz: "都", py: "dōu", vi: "đều", exHz: "我们都去学校。", exPy: "Wǒmen dōu qù xuéxiào.", exVi: "Chúng tôi đều đi đến trường." },
    { hz: "读", py: "dú", vi: "đọc", exHz: "她读书很快。", exPy: "Tā dúshū hěn kuài.", exVi: "Cô ấy đọc sách rất nhanh." },
    { hz: "对不起", py: "duìbùqǐ", vi: "xin lỗi", exHz: "对不起，我迟到了。", exPy: "Duìbuqǐ, wǒ chídào le.", exVi: "Xin lỗi, tôi đến muộn." },
    { hz: "多", py: "duō", vi: "nhiều", exHz: "我有很多书。", exPy: "Wǒ yǒu hěn duō shū.", exVi: "Tôi có nhiều sách." },
    { hz: "多少", py: "duōshǎo", vi: "bao nhiêu", exHz: "这本书多少钱？", exPy: "Zhè běn shū duōshǎo qián?", exVi: "Quyển sách này bao nhiêu tiền?" },
    { hz: "儿子", py: "érzi", vi: "con trai", exHz: "我的儿子很聪明。", exPy: "Wǒ de érzi hěn cōngmíng.", exVi: "Con trai của tôi rất thông minh." },
    { hz: "二", py: "èr", vi: "hai", exHz: "我喜欢“二”数字。", exPy: "Wǒ xǐhuān 'èr' shùzi", exVi: "Tôi thích số 2." },
    { hz: "饭馆", py: "fànguǎn", vi: "nhà hàng", exHz: "我们去饭馆吃饭。", exPy: "Wǒmen qù fànguǎn chīfàn.", exVi: "Chúng tôi đi nhà hàng ăn cơm." },
    { hz: "飞机", py: "fēijī", vi: "máy bay", exHz: "飞机很快。", exPy: "Fēijī hěn kuài.", exVi: "Máy bay thì nhanh." },
    { hz: "分钟", py: "fēnzhōng", vi: "phút", exHz: "他等了五分钟。", exPy: "Tā děngle wǔ fēnzhōng.", exVi: "Anh ấy đợi năm phút." },
    { hz: "高兴", py: "gāoxìng", vi: "vui", exHz: "我很高兴。", exPy: "Wǒ hěn gāoxìng.", exVi: "Tôi rất vui." },
    { hz: "个", py: "gè", vi: "cái (đơn vị lượng từ)", exHz: "我有一个钱包。", exPy: "Wǒ yǒu yī ge qiánbāo.", exVi: "Tôi có một cái ví tiền." },
    { hz: "工作", py: "gōngzuò", vi: "công việc", exHz: "我的工作很忙。", exPy: "Wǒ de gōngzuò hěn máng.", exVi: "Công việc của tôi rất bận." },
    { hz: "狗", py: "gǒu", vi: "chó", exHz: "这只狗很可爱。", exPy: "Zhè zhī gǒu hěn kě'ài.", exVi: "Con chó này rất dễ thương." },
    { hz: "汉语", py: "Hànyǔ", vi: "tiếng Hán", exHz: "我在学汉语。", exPy: "Wǒ zài xué Hànyǔ.", exVi: "Tôi đang học tiếng Trung." },
    { hz: "好", py: "hǎo", vi: "tốt, khỏe", exHz: "他很好。", exPy: "Tā hěn hǎo.", exVi: "Anh ấy rất tốt." },
    { hz: "喝", py: "hē", vi: "uống", exHz: "我喝水。", exPy: "Wǒ hē shuǐ.", exVi: "Tôi uống nước." },
    { hz: "和", py: "hé", vi: "và", exHz: "我和你一起去。", exPy: "Wǒ hé nǐ yīqǐ qù.", exVi: "Tôi và bạn cùng đi." },
    { hz: "很", py: "hěn", vi: "rất", exHz: "这个苹果很甜。", exPy: "Zhège píngguǒ hěn tián.", exVi: "Cái táo này rất ngọt." },
    { hz: "后面", py: "hòumiàn", vi: "phía sau", exHz: "我家在后面。", exPy: "Wǒ jiā zài hòumiàn.", exVi: "Nhà tôi ở phía sau." },
    { hz: "回", py: "huí", vi: "quay lại, về", exHz: "我回家了。", exPy: "Wǒ huí jiā le.", exVi: "Tôi đã về nhà." },
    { hz: "会", py: "huì", vi: "sẽ, biết (kỹ năng)", exHz: "我会说汉语。", exPy: "Wǒ huì shuō Hànyǔ.", exVi: "Tôi biết nói tiếng Trung." },
    { hz: "火车站", py: "huǒchēzhàn", vi: "ga tàu", exHz: "火车站在前面。", exPy: "Huǒchēzhàn zài qiánmiàn.", exVi: "Ga tàu ở phía trước." },
    { hz: "几", py: "jǐ", vi: "mấy", exHz: "你有几个苹果？", exPy: "Nǐ yǒu jǐ ge píngguǒ?", exVi: "Bạn có mấy quả táo?" },
    { hz: "家", py: "jiā", vi: "gia đình, nhà", exHz: "我家有四口人。", exPy: "Wǒ jiā yǒu sì kǒu rén.", exVi: "Nhà tôi có bốn người." },
    { hz: "叫", py: "jiào", vi: "gọi, tên gọi", exHz: "她叫李娜。", exPy: "Tā叫李娜。", exVi: "Cô ấy tên là Lý Na." },
    { hz: "今天", py: "jīntiān", vi: "hôm nay", exHz: "今天是星期一。", exPy: "Jīntiān shì xīngqī yī.", exVi: "Hôm nay là thứ Hai." },
    { hz: "九", py: "jiǔ", vi: "chín", exHz: "我有九本书。", exPy: "Wǒ yǒu jiǔ běn shū.", exVi: "Tôi có chín quyển sách." },
    { hz: "开", py: "kāi", vi: "mở, khởi động", exHz: "我们开车去。", exPy: "Wǒmen kāichē qù.", exVi: "Chúng tôi đi bằng ô tô." },
    { hz: "看", py: "kàn", vi: "xem", exHz: "我喜欢看电影。", exPy: "Wǒ xǐhuān kàn diànyǐng.", exVi: "Tôi thích xem phim." },
    { hz: "看见", py: "kànjiàn", vi: "nhìn thấy", exHz: "我看见你了。", exPy: "Wǒ kànjiàn nǐ le.", exVi: "Tôi đã thấy bạn." },
    { hz: "块", py: "kuài", vi: "miếng, đồng (tiền)", exHz: "这个苹果两块钱。", exPy: "Zhège píngguǒ liǎng kuài qián.", exVi: "Cái táo này hai tệ." },
    { hz: "来", py: "lái", vi: "đến", exHz: "明天我来。", exPy: "Míngtiān wǒ lái.", exVi: "Ngày mai tôi đến." },
    { hz: "老师", py: "lǎoshī", vi: "giáo viên", exHz: "我的老师很友好。", exPy: "Wǒ de lǎoshī hěn yǒuhǎo.", exVi: "Giáo viên của tôi rất thân thiện." },
    { hz: "了", py: "le", vi: "đã (dùng để chỉ sự thay đổi)", exHz: "她去了学校。", exPy: "Tā qùle xuéxiào.", exVi: "Cô ấy đã đi đến trường." },
    { hz: "冷", py: "lěng", vi: "lạnh", exHz: "外面很冷。", exPy: "Wàimiàn hěn lěng.", exVi: "Bên ngoài rất lạnh." },
    { hz: "里", py: "lǐ", vi: "trong", exHz: "我的书 zài 里面。", exPy: "Wǒ de shū zài lǐmiàn.", exVi: "Sách của tôi ở bên trong." },
    { hz: "零", py: "líng", vi: "không (số 0)", exHz: "今天零度。", exPy: "Jīntiān líng dù.", exVi: "Hôm nay không độ." },
    { hz: "六", py: "liù", vi: "sáu", exHz: "我有六个苹果。", exPy: "Wǒ yǒu liù ge píngguǒ.", exVi: "Tôi có sáu quả táo." },
    { hz: "妈妈", py: "māma", vi: "mẹ", exHz: "我的妈妈很漂亮。", exPy: "Wǒ de māmā hěn piàoliang.", exVi: "Mẹ của tôi rất xinh đẹp." },
    { hz: "吗", py: "ma", vi: "không (dùng trong câu hỏi)", exHz: "你好吗？", exPy: "Nǐ hǎo ma?", exVi: "Bạn khỏe không?" },
    { hz: "买", py: "mǎi", vi: "mua", exHz: "我买了水果。", exPy: "Wǒ mǎile shuǐguǒ.", exVi: "Tôi đã mua trái cây." },
    { hz: "猫", py: "māo", vi: "mèo", exHz: "这只猫很可爱。", exPy: "Zhè zhī māo hěn kě'ài.", exVi: "Con mèo này rất dễ thương." },
    { hz: "没", py: "méi", vi: "không có, chưa", exHz: "我没看见他。", exPy: "Wǒ méi kànjiàn tā.", exVi: "Tôi không nhìn thấy anh ấy." },
    { hz: "没关系", py: "méi guānxi", vi: "không sao, không có gì", exHz: "下雨了，没关系，我们有伞。", exPy: "Xiàyǔ le, méi guānxì, wǒmen yǒu sǎn.", exVi: "Trời mưa rồi, không sao đâu, chúng ta có ô." },
    { hz: "米饭", py: "mǐfàn", vi: "cơm", exHz: "我们吃米饭。", exPy: "Wǒmen chī mǐfàn.", exVi: "Chúng tôi ăn cơm." },
    { hz: "明天", py: "míngtiān", vi: "ngày mai", exHz: "明天见。", exPy: "Míngtiān jiàn.", exVi: "Ngày mai gặp." },
    { hz: "名字", py: "míngzi", vi: "tên", exHz: "你叫什么名字？", exPy: "Nǐ jiào shénme míngzì?", exVi: "Bạn tên là gì?" },
    { hz: "哪里", py: "nǎlǐ (nǎr)", vi: "đâu, chỗ nào", exHz: "你要去哪儿？", exPy: "Nǐ yào qù nǎr？", exVi: "Bạn muốn đi đâu?" },
    { hz: "那", py: "nà", vi: "đó, kia", exHz: "那个书包很漂亮。", exPy: "Nàge shūbāo hěn piàoliang.", exVi: "Cái cặp sách đó rất đẹp." },
    { hz: "呢", py: "ne", vi: "thì sao? (dùng để hỏi thêm)", exHz: "你呢？", exPy: "Nǐ ne?", exVi: "Còn bạn thì sao?" },
    { hz: "能", py: "néng", vi: "có thể", exHz: "他能说三种语言。", exPy: "Tā néng shuō sān zhǒng yǔyán.", exVi: "Anh ấy có thể nói ba ngôn ngữ." },
    { hz: "你", py: "nǐ", vi: "bạn", exHz: "你叫什么名字？", exPy: "Nǐ jiào shénme míngzi?", exVi: "Bạn tên là gì?" },
    { hz: "年", py: "nián", vi: "năm", exHz: "我结婚三年了。", exPy: "Wǒ jiéhūn sān nián le.", exVi: "Tôi kết hôn 3 năm rồi." },
    { hz: "女儿", py: "nǚ'ér", vi: "con gái", exHz: "她是我的女儿。", exPy: "Tā shì wǒ de nǚ'ér.", exVi: "Con bé là con gái của tôi." },
    { hz: "朋友", py: "péngyou", vi: "bạn", exHz: "她的朋友很聪明。", exPy: "Tā de péngyou hěn cōngmíng.", exVi: "Bạn của cô ấy rất thông minh." },
    { hz: "漂亮", py: "piàoliang", vi: "đẹp", exHz: "她很漂亮。", exPy: "Tā hěn piàoliang.", exVi: "Cô ấy rất xinh đẹp." },
    { hz: "苹果", py: "píngguǒ", vi: "táo", exHz: "这个苹果很好吃。", exPy: "Zhège píngguǒ hěn hǎochī.", exVi: "Táo này rất ngon." },
    { hz: "七", py: "qī", vi: "bảy", exHz: "我有七个朋友。", exPy: "Wǒ yǒu qī ge péngyou.", exVi: "Tôi có bảy người bạn." },
    { hz: "钱", py: "qián", vi: "tiền", exHz: "这本书多少钱？", exPy: "Zhè běn shū duōshǎo qián?", exVi: "Cuốn sách này giá bao nhiêu?" },
    { hz: "前面", py: "qiánmiàn", vi: "phía trước", exHz: "火车站在前面。", exPy: "Huǒchēzhàn zài qiánmiàn.", exVi: "Ga tàu ở phía trước." },
    { hz: "请", py: "qǐng", vi: "xin vui lòng, mời", exHz: "请给我菜单。", exPy: "Qǐng gěi wǒ càidān.", exVi: "Xin vui lòng đưa cho tôi thực đơn." },
    { hz: "去", py: "qù", vi: "đi", exHz: "我们要去商店。", exPy: "Wǒmen yào qù shāngdiàn.", exVi: "Chúng tôi phải đến cửa hàng." },
    { hz: "热", py: "rè", vi: "nóng", exHz: "天气很热。", exPy: "Tiānqì hěn rè.", exVi: "Thời tiết rất nóng." },
    { hz: "人", py: "rén", vi: "người", exHz: "这个人很友好。", exPy: "Zhè ge rén hěn yǒuhǎo.", exVi: "Người này rất thân thiện." },
    { hz: "认识", py: "rènshi", vi: "quen biết", exHz: "我认识他。", exPy: "Wǒ rènshi tā.", exVi: "Tôi quen anh ấy." },
    { hz: "日", py: "rì", vi: "ngày", exHz: "今天是几月几日？", exPy: "Jīntiān shì jǐ yuè jǐ rì?", exVi: "Hôm nay là ngày mấy tháng mấy?" },
    { hz: "三", py: "sān", vi: "ba", exHz: "我有三本书。", exPy: "Wǒ yǒu sān běn shū.", exVi: "Tôi có ba cuốn sách." },
    { hz: "商店", py: "shāngdiàn", vi: "cửa hàng", exHz: "这个商店很大。", exPy: "Zhège shāngdiàn hěn dà.", exVi: "Cửa hàng này rất lớn." },
    { hz: "上", py: "shàng", vi: "lên", exHz: "他在上楼。", exPy: "Tā zài shàng lóu.", exVi: "Anh ấy đang lên tầng." },
    { hz: "上午", py: "shàngwǔ", vi: "buổi sáng", exHz: "上午我们去学校。", exPy: "Shàngwǔ wǒmen qù xuéxiào.", exVi: "Vào buổi sáng chúng tôi đi học." },
    { hz: "少", py: "shǎo", vi: "ít", exHz: "我们还少一个人。", exPy: "Wǒmen hái shǎo yīgè rén.", exVi: "Chúng tôi vẫn thiếu một người." },
    { hz: "谁", py: "shéi", vi: "ai", exHz: "谁是你的老师？", exPy: "Shéi shì nǐ de lǎoshī?", exVi: "Ai là giáo viên của bạn?" },
    { hz: "什么", py: "shénme", vi: "cái gì", exHz: "你想吃什么？", exPy: "Nǐ xiǎng chī shénme?", exVi: "Bạn muốn ăn gì?" },
    { hz: "十", py: "shí", vi: "mười", exHz: "我有十块钱。", exPy: "Wǒ yǒu shí kuài qián.", exVi: "Tôi có mười tệ." },
    { hz: "时候", py: "shíhòu", vi: "lúc, khi", exHz: "你什么时候来？", exPy: "Nǐ shénme shíhòu lái?", exVi: "Bạn đến lúc nào ?" },
    { hz: "是", py: "shì", vi: "là, thì", exHz: "这是一本好书。", exPy: "Zhè shì yī běn hǎo shū.", exVi: "Đây là một cuốn sách hay." },
    { hz: "书", py: "shū", vi: "sách", exHz: "这本书很有意思。", exPy: "Zhè běn shū hěn yǒuyìsi.", exVi: "Cuốn sách này rất thú vị." },
    { hz: "水", py: "shuǐ", vi: "nước", exHz: "我喝水。", exPy: "Wǒ hē shuǐ.", exVi: "Tôi uống nước." },
    { hz: "水果", py: "shuǐguǒ", vi: "trái cây", exHz: "她喜欢吃水果。", exPy: "Tā xǐhuān chī shuǐguǒ.", exVi: "Cô ấy thích ăn trái cây." },
    { hz: "睡觉", py: "shuìjiào", vi: "ngủ", exHz: "他每天晚上十点睡觉。", exPy: "Tā měitiān wǎnshàng shí diǎn shuìjiào.", exVi: "Anh ấy đi ngủ lúc mười giờ tối mỗi ngày." },
    { hz: "说话", py: "shuōhuà", vi: "nói chuyện", exHz: "你怎么不说话？", exPy: "Nǐ zěnme bù shuōhuà?", exVi: "Sao bạn không nói chuyện thế?" },
    { hz: "四", py: "sì", vi: "bốn", exHz: "他们四个人去旅行。", exPy: "Tāmen sì gè rén qù lǚxíng.", exVi: "Bốn người họ đi du lịch." },
    { hz: "岁", py: "suì", vi: "tuổi", exHz: "我今年二十五岁。", exPy: "Wǒ jīnnián èrshíwǔ suì.", exVi: "Tôi năm nay hai mươi lăm tuổi." },
    { hz: "他", py: "tā", vi: "anh ấy, ông ấy", exHz: "他是我的朋友。", exPy: "Tā shì wǒ de péngyou.", exVi: "Anh ấy là bạn của tôi." },
    { hz: "她", py: "tā", vi: "cô ấy, bà ấy", exHz: "她在家里。", exPy: "Tā zài jiālǐ.", exVi: "Cô ấy ở nhà." },
    { hz: "太", py: "tài", vi: "quá", exHz: "今天太热了。", exPy: "Jīntiān tài rè le.", exVi: "Hôm nay nóng quá." },
    { hz: "天气", py: "tiānqì", vi: "thời tiết", exHz: "今天天气很好。", exPy: "Jīntiān tiānqì hěn hǎo.", exVi: "Thời tiết hôm nay rất tốt." },
    { hz: "听", py: "tīng", vi: "nghe", exHz: "我喜欢听音乐。", exPy: "Wǒ xǐhuān tīng yīnyuè.", exVi: "Tôi thích nghe nhạc." },
    { hz: "同学", py: "tóngxué", vi: "bạn học", exHz: "我们 shì 同学。", exPy: "Wǒmen shì tóngxué.", exVi: "Chúng tôi là bạn học." },
    { hz: "喂", py: "wèi", vi: "alo", exHz: "喂，你好吗？", exPy: "Wèi, nǐ hǎo ma?", exVi: "Alo, bạn khỏe không?" },
    { hz: "我", py: "wǒ", vi: "tôi", exHz: "我想喝水。", exPy: "Wǒ xiǎng hē shuǐ.", exVi: "Tôi muốn uống nước." },
    { hz: "Chúng tôi", py: "wǒmen", vi: "chúng tôi", exHz: "我们一起去吧。", exPy: "Wǒmen yīqǐ qù ba.", exVi: "Chúng ta cùng đi nhé." },
    { hz: "五", py: "wǔ", vi: "năm", exHz: "他有五本书。", exPy: "Tā yǒu wǔ běn shū.", exVi: "Anh ấy có năm cuốn sách." },
    { hz: "喜欢", py: "xǐhuān", vi: "thích", exHz: "我喜欢喝咖啡。", exPy: "Wǒ xǐhuān hē kāfēi.", exVi: "Tôi thích uống cà phê." },
    { hz: "下", py: "xià", vi: "xuống", exHz: "我在下楼。", exPy: "Wǒ zài xià lóu.", exVi: "Tôi đang xuống lầu." },
    { hz: "下午", py: "xiàwǔ", vi: "buổi chiều", exHz: "下午我们去逛街。", exPy: "Xiàwǔ wǒmen qù guàngjiē.", exVi: "Buổi chiều, chúng tôi đi dạo phố." },
    { hz: "下雨", py: "xià yǔ", vi: "mưa", exHz: "外面下雨了，记得带伞。", exPy: "Wàimiàn xià yǔ le, jìdé dài sǎn.", exVi: "Ngoài trời mưa, nhớ mang theo ô." },
    { hz: "先生", py: "xiānshēng", vi: "ông, ngài", exHz: "先生，这边请。", exPy: "Xiānshēng, zhè biān qǐng", exVi: "Mời anh qua bên này." },
    { hz: "现在", py: "xiànzài", vi: "bây giờ", exHz: "我现在很累。", exPy: "Wǒ xiànzài hěn lèi.", exVi: "Tôi hiện tại rất mệt." },
    { hz: "想", py: "xiǎng", vi: "nghĩ, muốn", exHz: "我想去看电影。", exPy: "Wǒ xiǎng qù kàn diànyǐng.", exVi: "Tôi muốn đi xem phim." },
    { hz: "小", py: "xiǎo", vi: "nhỏ", exHz: "这是一只小狗。", exPy: "Zhè shì yī zhī xiǎo gǒu.", exVi: "Đây là một chú chó con." },
    { hz: "小姐", py: "xiǎojiě", vi: "cô (trong cách gọi)", exHz: "小姐，请问这里有洗手间吗？", exPy: "Xiǎojiě, qǐngwèn zhèlǐ yǒu xǐshǒujiān ma?", exVi: "Cô ơi, xin hỏi ở đây có nhà vệ sinh không?" },
    { hz: "些", py: "xiē", vi: "vài", exHz: "我们买了一些水果。", exPy: "Wǒmen mǎile yīxiē shuǐguǒ.", exVi: "Chúng tôi đã mua một ít trái cây." },
    { hz: "写", py: "xiě", vi: "viết", exHz: "我正在写信。", exPy: "Wǒ zhèngzài xiě xìn.", exVi: "Tôi đang viết thư." },
    { hz: "谢谢", py: "xièxiè", vi: "cảm ơn", exHz: "谢谢你的帮助。", exPy: "Xièxiè nǐ de bāngzhù.", exVi: "Cảm ơn sự giúp đỡ của bạn." },
    { hz: "星期", py: "xīngqī", vi: "tuần", exHz: "一个星期就好。", exPy: "Yí gè xīngqī jiǔ hǎo.", exVi: "Một tuần là được" },
    { hz: "学生", py: "xuéshēng", vi: "học sinh", exHz: "他是一个好学生。", exPy: "Tā shì yīgè hǎo xuéshēng.", exVi: "Anh ấy là một học sinh giỏi." },
    { hz: "学习", py: "xuéxí", vi: "học tập", exHz: "学习中文很有趣。", exPy: "Xuéxí zhōngwén hěn yǒuqù.", exVi: "Học tiếng Trung rất thú vị." },
    { hz: "学校", py: "xuéxiào", vi: "trường học", exHz: "我在学校学习中文。", exPy: "Wǒ zài xuéxiào xuéxí zhōngwén.", exVi: "Tôi học tiếng Trung ở trường." },
    { hz: "一", py: "yī", vi: "một", exHz: "一个人在公园散步。", exPy: "Yī gè rén zài gōngyuán sànbù.", exVi: "Một người đang đi dạo trong công viên." },
    { hz: "衣服", py: "yīfu", vi: "quần áo", exHz: "这件衣服很漂亮。", exPy: "Zhè jiàn yīfu hěn piàoliang.", exVi: "Bộ quần áo này rất đẹp." },
    { hz: "医生", py: "yīshēng", vi: "bác sĩ", exHz: "他是一位医生。", exPy: "Tā shì yī wèi yīshēng.", exVi: "Anh ấy là một bác sĩ." },
    { hz: "医院", py: "yīyuàn", vi: "bệnh viện", exHz: "我们去医院看病。", exPy: "Wǒmen qù yīyuàn kàn bìng.", exVi: "Chúng tôi đến bệnh viện để khám bệnh." },
    { hz: "椅子", py: "yǐzi", vi: "ghế", exHz: "请坐在椅子上。", exPy: "Qǐng zuò zài yǐzi shàng.", exVi: "Xin ngồi lên ghế." },
    { hz: "月", py: "yuè", vi: "tháng, mặt trăng", exHz: "这个月我很忙。", exPy: "Zhège yuè wǒ hěn máng.", exVi: "Tháng này tôi rất bận." },
    { hz: "在", py: "zài", vi: "ở, tại", exHz: "他在学校学习。", exPy: "Tā zài xuéxiào xuéxí.", exVi: "Anh ấy học ở trường." },
    { hz: "再见", py: "zàijiàn", vi: "tạm biệt", exHz: "我们明天再见。", exPy: "Wǒmen míngtiān zàijiàn.", exVi: "Chúng ta gặp lại vào ngày mai." },
    { hz: "怎么", py: "zěnme", vi: "làm sao", exHz: "你怎么了？", exPy: "Nǐ zěnme le?", exVi: "Bạn sao vậy?" },
    { hz: "怎么样", py: "zěnmeyàng", vi: "như thế nào", exHz: "你的工作怎么样？", exPy: "Nǐ de gōngzuò zěnmeyàng?", exVi: "Công việc của bạn thế nào?" },
    { hz: "这", py: "zhè", vi: "Đây, này", exHz: "这件事怎么样？", exPy: "Zhè jiàn shì zěnme yàng?", exVi: "Việc này như thế nào?" },
    { hz: "中国", py: "Zhōngguó", vi: "Trung Quốc", exHz: "中国有很多美丽的风景。", exPy: "Zhōngguó yǒu hěn duō měilì de fēngjǐng.", exVi: "Trung Quốc có nhiều cảnh đẹp." },
    { hz: "中午", py: "zhōngwǔ", vi: "buổi trưa", exHz: "中午我们去吃饭吧。", exPy: "Zhōngwǔ wǒmen qù chīfàn ba.", exVi: "Buổi trưa chúng ta đi ăn cơm nhé." },
    { hz: "住", py: "zhù", vi: "sống, cư trú", exHz: "我住在一个很安静的地方。", exPy: "Wǒ zhù zài yīgè hěn ānjìng de dìfāng.", exVi: "Tôi sống ở một nơi rất yên tĩnh." },
    { hz: "桌子", py: "zhuōzi", vi: "bàn", exHz: "桌子上放着一本书。", exPy: "Zhuōzi shàng fàngzhe yī běn shū.", exVi: "Trên bàn có một cuốn sách." },
    { hz: "字", py: "zì", vi: "chữ", exHz: "我们要学会写字。", exPy: "Wǒmen yào xuéhuì xiě zì.", exVi: "Chúng ta phải học viết chữ." },
    { hz: "昨天", py: "zuótiān", vi: "hôm qua", exHz: "昨天我去看了一部电影。", exPy: "Zuótiān wǒ qù kànle yī bù diànyǐng.", exVi: "Hôm qua tôi đã đi xem một bộ phim." },
    { hz: "坐", py: "zuò", vi: "ngồi", exHz: "我们在公园里坐了一会儿。", exPy: "Wǒmen zài gōngyuán lǐ zuòle yīhuìr.", exVi: "Chúng tôi đã ngồi một lúc trong công viên." },
    { hz: "做", py: "zuò", vi: "làm", exHz: "他正在做作业。", exPy: "Tā zhèngzài zuò zuòyè.", exVi: "Anh ấy đang làm bài tập về nhà." }
];