// hsk1-data.js
// HSK 1 vocabulary data

const WORDS = [
  { hanzi: "爱", pinyin: "ài", vi: "yêu" },
  { hanzi: "八", pinyin: "bā", vi: "tám" },
  { hanzi: "爸爸", pinyin: "bàba", vi: "bố" },
  { hanzi: "杯子", pinyin: "bēizi", vi: "cốc" },
  { hanzi: "北京", pinyin: "Běijīng", vi: "Bắc Kinh" },
  { hanzi: "本", pinyin: "běn", vi: "cuốn (dùng cho sách)" },
  { hanzi: "不客气", pinyin: "bú kèqì", vi: "không có gì (đáp lại lời cảm ơn)" },
  { hanzi: "不", pinyin: "bù", vi: "không" },
  { hanzi: "菜", pinyin: "cài", vi: "món ăn, rau củ" },
  { hanzi: "茶", pinyin: "chá", vi: "trà" },
  { hanzi: "吃", pinyin: "chī", vi: "ăn" },
  { hanzi: "出租车", pinyin: "chūzūchē", vi: "taxi" },
  { hanzi: "打电话", pinyin: "dǎ diànhuà", vi: "gọi điện thoại" },
  { hanzi: "大", pinyin: "dà", vi: "lớn, to" },
  { hanzi: "的", pinyin: "de", vi: "của (thuộc tính)" },
  { hanzi: "点", pinyin: "diǎn", vi: "giờ (trong thời gian)" },
  { hanzi: "电脑", pinyin: "diànnǎo", vi: "máy tính" },
  { hanzi: "电视", pinyin: "diànshì", vi: "ti vi" },
  { hanzi: "电影", pinyin: "diànyǐng", vi: "phim" },
  { hanzi: "东西", pinyin: "dōngxī", vi: "đồ vật, thứ" },
  { hanzi: "都", pinyin: "dōu", vi: "đều" },
  { hanzi: "读", pinyin: "dú", vi: "đọc" },
  { hanzi: "对不起", pinyin: "duìbùqǐ", vi: "xin lỗi" },
  { hanzi: "多", pinyin: "duō", vi: "nhiều" },
  { hanzi: "多少", pinyin: "duōshǎo", vi: "bao nhiêu" },
  { hanzi: "儿子", pinyin: "érzi", vi: "con trai" },
  { hanzi: "二", pinyin: "èr", vi: "hai" },
  { hanzi: "饭馆", pinyin: "fànguǎn", vi: "nhà hàng" },
  { hanzi: "飞机", pinyin: "fēijī", vi: "máy bay" },
  { hanzi: "分钟", pinyin: "fēnzhōng", vi: "phút" },
  { hanzi: "高兴", pinyin: "gāoxìng", vi: "vui" },
  { hanzi: "个", pinyin: "gè", vi: "cái (lượng từ)" },
  { hanzi: "工作", pinyin: "gōngzuò", vi: "công việc" },
  { hanzi: "狗", pinyin: "gǒu", vi: "chó" },
  { hanzi: "汉语", pinyin: "Hànyǔ", vi: "tiếng Hán" },
  { hanzi: "好", pinyin: "hǎo", vi: "tốt, khỏe" },
  { hanzi: "喝", pinyin: "hē", vi: "uống" },
  { hanzi: "和", pinyin: "hé", vi: "và" },
  { hanzi: "很", pinyin: "hěn", vi: "rất" },
  { hanzi: "后面", pinyin: "hòumiàn", vi: "phía sau" },
  { hanzi: "回", pinyin: "huí", vi: "quay lại, về" },
  { hanzi: "会", pinyin: "huì", vi: "sẽ, biết (kỹ năng)" },
  { hanzi: "火车站", pinyin: "huǒchēzhàn", vi: "ga tàu" },
  { hanzi: "几", pinyin: "jǐ", vi: "mấy" },
  { hanzi: "家", pinyin: "jiā", vi: "gia đình, nhà" },
  { hanzi: "叫", pinyin: "jiào", vi: "gọi, tên gọi" },
  { hanzi: "今天", pinyin: "jīntiān", vi: "hôm nay" },
  { hanzi: "九", pinyin: "jiǔ", vi: "chín" },
  { hanzi: "开", pinyin: "kāi", vi: "mở, khởi động" },
  { hanzi: "看", pinyin: "kàn", vi: "xem" },
  { hanzi: "看见", pinyin: "kànjiàn", vi: "nhìn thấy" },
  { hanzi: "块", pinyin: "kuài", vi: "miếng, đồng (tiền)" },
  { hanzi: "来", pinyin: "lái", vi: "đến" },
  { hanzi: "老师", pinyin: "lǎoshī", vi: "giáo viên" },
  { hanzi: "了", pinyin: "le", vi: "đã (chỉ sự thay đổi)" },
  { hanzi: "冷", pinyin: "lěng", vi: "lạnh" },
  { hanzi: "里", pinyin: "lǐ", vi: "trong" },
  { hanzi: "零", pinyin: "líng", vi: "không (số 0)" },
  { hanzi: "六", pinyin: "liù", vi: "sáu" },
  { hanzi: "妈妈", pinyin: "māma", vi: "mẹ" },
  { hanzi: "吗", pinyin: "ma", vi: "không? (câu hỏi)" },
  { hanzi: "买", pinyin: "mǎi", vi: "mua" },
  { hanzi: "猫", pinyin: "māo", vi: "mèo" },
  { hanzi: "没", pinyin: "méi", vi: "không có, chưa" },
  { hanzi: "没关系", pinyin: "méi guānxi", vi: "không sao" },
  { hanzi: "米饭", pinyin: "mǐfàn", vi: "cơm" },
  { hanzi: "明天", pinyin: "míngtiān", vi: "ngày mai" },
  { hanzi: "名字", pinyin: "míngzi", vi: "tên" },
  { hanzi: "哪里", pinyin: "nǎlǐ", vi: "đâu, chỗ nào" },
  { hanzi: "那", pinyin: "nà", vi: "đó, kia" },
  { hanzi: "你", pinyin: "nǐ", vi: "bạn" },
  { hanzi: "我们", pinyin: "wǒmen", vi: "chúng tôi" }
];

// dùng cho <script>
window.HSK1_WORDS = WORDS;
